#!/bin/bash
# make directory and change current directory to created directory
function mcd () { md -p $1; cd $1 }
function helpless() { $1 --help | less }
function showman() { man $1 | less }

# source overrides
if [ -f "$ZSH_CUSTOM/overrides/functions" ]
then
    source $ZSH_CUSTOM/overrides/functions
fi
