#!/usr/bin/env zsh
# zsh
alias zshrc="source $HOME/.zshrc"
alias zshconfig="code $HOME/.zshrc"

# neovim
alias nv="nvim"

# general
alias :q="exit"
alias :Q="exit"

# git
alias gh="git log --oneline --graph --pretty"
alias gcv="git commit -v"
alias gcav="git commit --amend -v"
alias gc="git fetch && git checkout"

#tmux
# alias tm="tmux"
# alias tps="tmux list-sessions"
# alias tkl="tmux kill-server"

# docker
alias dps="docker ps --format=\$DOCKER_FORMAT"
alias dc="docker-compose"
alias dcps="docker-compose ps"
alias dcup="docker-compose up -d"
alias dcdn="docker-compose down -v"
alias dcst="docker-compose start"
alias dcstp="docker-compose stop"

# ssh
alias s="kitty +kitten ssh"

# unaliase for bin overrides
unalias ls

# source overrides
if [ -f "$HOME/env/overrides/aliases" ]
then
    source "$HOME/env/overrides/aliases"
fi
