#!/usr/bin/env zsh
# make directory and change current directory to created directory
function mcd () { md -p $1; cd $1 }
function helpless() { $* --help | less }

function batman() { man $1 | bat --color always }

function finder() {
    dir=$(fd -L --full-path ~ ~/work --min-depth 1 -d 3 -t d --and ".*$1.*" | fzf)
    echo "cd $dir"
    cd $dir
}

# docker
function dbash() {
    docker exec -it "$1" bash
    if [ $? != 0 ]; then
        docker exec -it "$1" sh
    fi
}

function dl() {
    docker logs "$1" | less
}

compdef mcd=mkdir
compdef batman=man

# source overrides
if [ -f "$HOME/env/overrides/functions" ]
then
    source "$HOME/env/overrides/functions"
fi
