#!/usr/bin/env zsh

# always add files to completion options
function _add_files_to_completion() {
    _files
}
compdef _add_files_to_completion -first-

# source overrides
if [ -f "$HOME/env/overrides/misc" ]
then
    source "$HOME/env/overrides/misc"
fi

source "$HOME/.config/terrainium/terrainium_init"
