#!/usr/bin/env zsh
# zsh-completions
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

# source overrides
if [ -f "$HOME/env/overrides/misc" ]
then
    source "$HOME/env/overrides/misc"
fi

source "$HOME/.config/terrainium/terrainium_init"
