- name: Add neovim unstable PPA (Apt)
  become: yes
  apt_repository:
    repo: ppa:neovim-ppa/unstable
  tags:
    - cli
    - nvim
    - essentials

- name: nvim-nightly install (Apt)
  become: yes
  apt:
    name: neovim
    update_cache: true
  tags:
    - cli
    - nvim
    - essentials

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# TODO: change focal to pickup actual ubuntu version repo
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: add docker usergroup
  become: yes
  group:
    name: docker
    state: present
    gid: 1750

- name: add user to docker group
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: docker

- name: enable docker service
  become: yes
  systemd:
    name: docker
    state: started
    enabled: true
