- name: Stowing Dotfiles (Linux)
  shell: cd ~/dotfiles && DOTFILES=~/dotfiles ./scripts/setup common
  tags:
  - dotfiles

- name: create kitty desktop file (Linux)
  shell: cd ~/dotfiles/kitty/.config/kitty && ./kitty-desktop
  tags:
  - kitty
