#!/bin/bash

readonly SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
readonly CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}

function log(){
    printf  "\n[$(date)] $1 \n\n"
}

readonly CONFIG_DIR="$HOME/.config"

if [ -d "$HOME/.config" ]; then
    log "XDCONFIG Dir: $CONFIG_DIR"
else
    mkdir $CONFIG_DIR
fi

log "XDCONFIG Dir -> $CONFIG_DIR"
log "Config Dir -> $SCRIPT_DIR"

## declare an array variable
declare -a utils=("kitty" "neofetch" "nvim" "skhd" "yabai")

## now loop through the above array
for util in "${utils[@]}"
do
    if [ -L "$CONFIG_DIR/$util" ]; then
        log "Unlinking $SCRIPT_DIR/$util -> $CONFIG_DIR/$util"
        rm $CONFIG_DIR/$util
    else
        log "$util not linked"
    fi
done

if [ -e "$HOME/dotfiles" ]; then
    log "Unlinking $SCRIPTS_DIR -> $HOME/dotfiles"
    rm "$HOME/dotfiles"
else
        log "$HOME/dotfiles not linked"
fi

if [ -e "$HOME/.tmux.conf" ]; then
    log "Unlinking $SCRIPTS_DIR/.tmux.conf -> $HOME/.tmux.conf"
    rm "$HOME/.tmux.conf"
else
        log "$HOME/.tmux.conf not linked"
fi

if [ -e "$HOME/.ideavimrc" ]; then
    log "Unlinking $SCRIPTS_DIR/.ideavimrc -> $HOME/.ideavimrc"
    rm "$HOME/.ideavimrc"
else
        log "$HOME/.ideavimrc not linked"
fi

if [ -e "$CUSTOM/overrides" ]; then
    rm $CUSTOM/aliases
    rm $CUSTOM/env-vars
    rm $CUSTOM/functions
    rm $CUSTOM/misc
    rm $CUSTOM/overrides
else
    log "env-vars, overrides are not linked"
fi
