#!/usr/bin/env sh
CONFIG_DIR="$HOME/.config/sketchybar"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

sketchybar --bar height=55 \
	blur_radius=0 \
	position=bottom \
	sticky=off \
	padding_left=10 \
	padding_right=10 \
	y_offset=0 \
	color=$BACKGROUND

sketchybar --default updates=when_shown \
	drawing=on \
	icon.font="SpaceMono Nerd Font:Bold:17.0" \
	icon.color=$BACKGROUND \
	icon.padding_left=4 \
	icon.padding_right=4 \
	label.font="Jetbrains Mono:Bold:15.0" \
	label.padding_left=10 \
	label.padding_right=10 \
	background.drawing=off \

# add items
sketchybar --add item space_display left

sketchybar --add item focused_window center

sketchybar --add alias "Control Centre,Sound" right
sketchybar --add alias "Control Centre,Battery" right
sketchybar --add alias "Control Centre,WiFi" right
sketchybar --add alias "Amphetamine,Amphetamine" right
sketchybar --add alias "Mullvad VPN,Item-0" right

# ADD SUBSCRIPTIONS
sketchybar --subscribe space_display space_change
sketchybar --subscribe focused_window front_app_switched

sketchybar --update

sketchybar --set focused_window \
	label="~" \
    label.color=$ACCENT1 \
	icon.drawing=off \
	script="$PLUGIN_DIR/front_app.sh"

sketchybar --set space_display \
	label="1" \
    label.color=$ACCENT1 \
	icon.drawing=off \
	script="$PLUGIN_DIR/space.sh"

echo "sketchybar configuration loaded.."
