#!/usr/bin/env sh
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
ITEMS_DIR="$HOME/.config/sketchybar/items"

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

# CREATE BAR
sketchybar --bar height=30 \
	blur_radius=0 \
	position=top \
	sticky=off \
	padding_left=10 \
	padding_right=10 \
	y_offset=0 \
	color=$BACKGROUND

# SET DEFAULTS
sketchybar --default updates=when_shown \
	drawing=on \
	icon.drawing=off \
	icon.font="SpaceMono Nerd Font:Bold:17.0" \
	icon.color=$ACCENT1 \
	icon.padding_left=4 \
	icon.padding_right=4 \
	label.drawing=off \
	label.font="Jetbrains Mono:Bold:15.0" \
	label.color=$FOREGROUND \
	label.padding_left=10 \
	label.padding_right=10 \
	background.drawing=off \
	popup.background.color=$BACKGROUND

# ADD ITEMS
# left
source "$ITEMS_DIR/ispace.sh"
source "$ITEMS_DIR/iwindow.sh"

# right
source "$ITEMS_DIR/iclock.sh"
source "$ITEMS_DIR/ivpn.sh"
source "$ITEMS_DIR/iwifi.sh"
source "$ITEMS_DIR/ibattery.sh"
source "$ITEMS_DIR/isound.sh"
source "$ITEMS_DIR/ialiases.sh"

sketchybar --update

echo "sketchybar configuration loaded.."
