#!/usr/bin/env sh
CONFIG_DIR="$HOME/.config/sketchybar/"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEMS_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh"

sketchybar --bar height=55                                          \
                 blur_radius=0                                      \
                 position=bottom                                    \
                 sticky=off                                         \
                 padding_left=10                                    \
                 padding_right=10                                   \
                 y_offset=0                                         \
                 color=$BACKGROUND                                  \

sketchybar --default updates=when_shown                             \
                     drawing=on                                     \
                     icon.font="SpaceMono Nerd Font:Bold:17.0"      \
                     icon.color=$FOREGROUND                         \
                     icon.padding_left=4                            \
                     icon.padding_right=4                           \
                     label.font="Victor Mono:Bold:15.0"             \
                     label.color=$FOREGROUND                        \
                     label.padding_left=4                           \
                     label.padding_right=4                          \

source "$ITEMS_DIR/spaces.sh"

sketchybar --add item space_separator center                        \
           --set space_separator icon=                             \
                                 icon.color=$ACCENT                 \
                                 background.padding_left=4          \
                                 background.padding_right=2         \
                                 label.drawing=off                  \

sketchybar --add item front_app center                              \
           --set front_app script="$PLUGIN_DIR/front_app.sh "       \
                           icon.drawing=off                         \
                           label.color=$ACCENT                      \
                           label.padding_right=10                   \
           --subscribe front_app front_app_switched

sketchybar --add item clock right                                  \
           --set clock   update_freq=10                            \
                         script="$PLUGIN_DIR/clock.sh"             \
           --add item battery right                                \
           --set battery script="$PLUGIN_DIR/battery.sh"           \
                         update_freq=10                            \
           --subscribe battery system_woke

sketchybar --update

echo "sketchybar configuration loaded.."
