- name: nvim-nightly install (Brew)
  ansible.builtin.homebrew:
    name: nvim
    state: head
  tags:
    - cli
    - nvim
    - essentials

- name: kitty install (shell) (Darwin)
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    creates: /Applications/kitty.app
  tags:
    - gui
    - kitty

- name: Dotfiles Setup (Darwin)
  shell: cd ~/dotfiles && DOTFILES=~/dotfiles ./scripts/setup darwin
  tags:
    - dotfiles

- name: enable sketchybar service (Brew)
  shell: brew services start sketchybar
  tags:
    - gui
    - de

- name: enable skhd service (Brew)
  shell: brew services start skhd
  tags:
    - gui
    - de

- name: Create a fonts directory if it does not exist (Darwin)
  file:
    path: ~/Library/Fonts
    state: directory
    mode: '0755'
  tags: dotfiles

- name: Copy fonts (Darwin)
  copy:
    src: ~/dotfiles/fonts/
    dest: ~/Library/Fonts
  tags: dotfiles
