#!/usr/bin/env sh

### Load scripting addition ###
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


### Settings ###
# External bar
yabai -m config external_bar all:0:0

# Global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config insert_feedback_color        0xfffc618d
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

yabai -m config window_border                off
yabai -m config window_border_hidpi          on
yabai -m config window_border_blur           off
yabai -m config window_border_width          1
yabai -m config window_border_radius         0
yabai -m config active_window_border_color   0xffBFBFBF
yabai -m config normal_window_border_color   0xff69676c

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# General space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  3
yabai -m config bottom_padding               60
yabai -m config left_padding                 3
yabai -m config right_padding                3
yabai -m config window_gap                   3

# Rules
yabai -m rule --add app="^System Settings$"                         manage=off
yabai -m rule --add app="^System Information$"                      manage=off
yabai -m rule --add app="^Finder$" title="(Info|Preferences)"       manage=off
yabai -m rule --add app="^Calculator$"                              manage=off
yabai -m rule --add app="^Activity Monitor$"                        manage=off
yabai -m rule --add app="^Font Book$"                               manage=off
yabai -m rule --add app="^Archive Utility$"                         manage=off
yabai -m rule --add app="^App Store$" label="App Store"             manage=off
yabai -m rule --add app="^Installer$"                               manage=off
yabai -m rule --add app="^Digital Colour Meter"                     manage=off
yabai -m rule --add app="^Mullvad VPN"                              manage=off mouse_follows_focus=off
yabai -m rule --add app="^JetBrains Toolbox"                        manage=off mouse_follows_focus=off
yabai -m rule --add app="^Wine*"                                    manage=off mouse_follows_focus=off
yabai -m rule --add app="^CleanMyMac*"                              manage=off
yabai -m rule --add app="^Alfred*"                              manage=off

echo "yabai configuration loaded.."
