#!/usr/bin/env sh

### Load scripting addition ###
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


### Settings ###
# External bar
yabai -m config external_bar all:35:0

# Global settings
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config insert_feedback_color        0xfffc618d
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

yabai -m config window_border                off
yabai -m config window_border_hidpi          on
yabai -m config window_border_blur           off
yabai -m config window_border_width          1
yabai -m config window_border_radius         0
yabai -m config active_window_border_color   0xffBFBFBF
yabai -m config normal_window_border_color   0xff69676c

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# General space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# layout rules
yabai -m config --space 6 layout stack
yabai -m config --space 7 layout stack
yabai -m config --space 8 layout stack
yabai -m config --space 10 layout stack
yabai -m config --space 11 layout stack

# events for sketchybar
yabai -m signal --add event=window_focused action='sketchybar --trigger window_focus ID="$YABAI_WINDOW_ID"'
yabai -m signal --add event=window_created action='sketchybar --trigger window_added ID="$YABAI_WINDOW_ID"'
yabai -m signal --add event=window_destroyed action='sketchybar --trigger window_destroyed ID="$YABAI_WINDOW_ID"'

# Rules
source $HOME/.config/yabai/rules

echo "yabai configuration loaded.."
