#!/usr/bin/env bash
set -e

install_pip() {
	unameOut="$(uname -s)"

	case "${unameOut}" in
	Linux*)
		if command -v apt-get &>/dev/null; then
			sudo apt update
			sudo apt install -y python3-venv sshpass
		elif command -v dnf &>/dev/null; then
			python3 -m ensurepip --upgrade
			sudo dnf install -y sshpass
		else
			echo "Unsupported Linux package manager on ${unameOut}" >&2
			exit 1
		fi
		;;
	Darwin*)
		python3 -m ensurepip --upgrade
		brew install sshpass
		;;
	*)
		echo "Unsupported OS: ${unameOut}" >&2
		exit 1
		;;
	esac
}

if command -v ansible &>/dev/null; then
	echo "ansible already installed"
else
	install_pip
	python3 -m pip install --user pipx
	pipx ensurepath
	pipx install --include-deps ansible
	# needed for json querying
	pipx inject --include-deps ansible jmespath ansible-lint
fi
