#!/usr/bin/env bash

which ansible
RESULT=$?

if [ $RESULT == 0 ]; then
    echo "ansible already installed"
else
    python -m ensurepip --upgrade
    pip install pipx
    pipx ensurepath
    pipx install --include-deps ansible
    # needed for json querying
    pipx inject ansible jmespath
fi
