#!/usr/bin/env bash

### Load scripting addition ###
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

### Settings ###
# External bar
yabai -m config external_bar all:0:45

# Global settings
yabai -m config window_placement             second_child
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config insert_feedback_color        0xfffc618d
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# General space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

borders active_color=0xffD4D4D4 inactive_color=0xff606060 width=5.0 &

source ~/.config/yabai/rules.sh

echo "yabai configuration loaded.."
