#!/usr/bin/env bash

### Load scripting addition ###
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

### Settings ###
# External bar
yabai -m config external_bar all:45:0

# Global settings
yabai -m config window_placement             second_child
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        1.0

yabai -m config insert_feedback_color        0xfffc618d
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# General space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# layout rules
yabai -m config --space 1 layout            stack
yabai -m config --space 2 layout            stack
yabai -m config --space 3 layout            stack
yabai -m config --space 5 layout            stack
yabai -m config --space 6 layout            stack

# labels to spaces
yabai -m space 1 --label term
yabai -m space 2 --label browser
yabai -m space 3 --label media
yabai -m space 5 --label files
yabai -m space 6 --label utils
yabai -m space 7 --label term
yabai -m space 8 --label browser
yabai -m space 9 --label media
yabai -m space 0 --label utils

echo "yabai configuration loaded.."
