#!/bin/bash

# Terminate already running bar instances
if pgrep -x polybar >/dev/null; then
  killall -q polybar
fi

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do
  sleep 1
done

# available polybar configs
readarray -d '' avail_configs < <(find $HOME/.config/polybar/ -maxdepth 1 -type f -name '*.ini' -print0)

# Launch Polybar, using default config location ~/.config/polybar/config
if type "xrandr"; then
  # for all monitors
  for monitor in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    # available polybar configs
    for config in "${avail_configs[@]}"; do
      BAR_NAME=$(echo $config | sed 's/.*\///' | sed -e 's/config.\(.*\).ini/\1/')
      echo $monitor
      echo $config
      echo $BAR_NAME
      MONITOR=${monitor} polybar -c=$config --reload $BAR_NAME &
    done
  done
else
  for config in "${avail_configs[@]}"; do
    BAR_NAME=$(echo $config | sed 's/.*\///' | sed -e 's/config.\(.*\).ini/\1/')
    polybar -c=$config --reload $BAR_NAME &
  done
fi
echo "Polybar launched..."
