#!/bin/bash

[[ -z "${CONFIG}" ]] && CONFIG='/home/chaitanya/.config' || CONFIG="${CONFIG}"

# Terminate already running bar instances
if pgrep -x polybar >/dev/null
then
  killall -q polybar
fi

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1;echo ; done

# Launch Polybar, using default config location ~/.config/polybar/config
if type "xrandr"; then
  # available polybar configs
  avail_outputs=($(find $CONFIG/polybar -maxdepth 1 -type f -name '*.ini'))
  # for all monitors
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
  echo $m
    # available polybar configs
    for u in "${avail_outputs[@]}"
    do
      polybar -c=$u --reload $(echo $u | sed 's/.*\///' | sed -e 's/config.\(.*\).ini/\1/') &
    done
  done
else
    for u in "${avail_outputs[@]}"
    do
      polybar -c=$u --reload $(echo $u | sed 's/.*\///' | sed -e 's/config.\(.*\).ini/\1/') &
    done
fi
echo "Polybar launched..."
