#!/usr/bin/env bash

if [ "$(playerctl -a status )" = "Stopped" ]; then
    echo "No music is playing"
elif [ "$(playerctl status )" = "Paused"  ]; then
    polybar-msg -p "$(pgrep -f "polybar now-playing")" hook player-play-pause 0 1>/dev/null 2>&1
    playerctl metadata --format "{{ title }} - {{ artist }}"
else # Can be configured to output differently when player is paused
    polybar-msg -p "$(pgrep -f "polybar now-playing")" hook player-play-pause 1 1>/dev/null 2>&1
    playerctl metadata --format "{{ title }} - {{ artist }}"
fi