#!/usr/bin/env bash

# Terminate already running bar instances
if pgrep -x polybar >/dev/null; then
  # killall -q polybar
  polybar-msg cmd quit
fi

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do
  sleep 1
done

# available polybar configs
if [ "$BAR_NAME" = "bottom-bar" ]; then
  avail_configs=(bottom-bar)
elif [ "$BAR_NAME" = "bottom-bar-rounded" ]; then
  avail_configs=(bottom-bar-rounded)
else
    avail_configs=(top bottom)
fi

config="$HOME/.config/polybar/config.ini"

# Launch Polybar, using default config location ~/.config/polybar/config
if type "xrandr"; then
  # for all monitors
  for monitor in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    # available polybar configs
    for bar in "${avail_configs[@]}"; do
      echo "$monitor"
      echo "$config"
      echo "$BAR_NAME"
      MONITOR=${monitor} polybar -c="$config" --reload "$bar" &
    done
  done
else
  for bar in "${avail_configs[@]}"; do
    polybar -c="$config" --reload "$bar" &
  done
fi
echo "Polybar launched.."
