#!/usr/bin/env bash
active_window_ids=($(
	xdotool search --all --onlyvisible --desktop $(xprop -notype -root _NET_CURRENT_DESKTOP | cut -c 24-) "" 2>/dev/null
))

active_windows_reverse=($(
	printf '%s\n' "${active_window_ids[@]}" | tac | tr '\n' ' '
	echo
))

declare -a active_windows

for window in "${active_window_ids[@]}"; do
	if [ "$window" = "$(xdotool getwindowfocus)" ]; then
		active_windows+=("%{F#1DE9B6}$(xdotool getwindowname "$window" | cut -c-30)%{F-}")
	else
		active_windows+=($(xdotool getwindowname "$window"))
	fi
done

printf -v joined '%s  ' "${active_windows[@]}"
echo "${joined%,}"
