#!/usr/bin/env bash
ITEMS_DIR="$HOME/.config/sketchybar/items"

source "$HOME/.config/sketchybar/colors.sh"
source "$HOME/.config/sketchybar/icons.sh"

separator() {
	sketchybar --query separator &>/dev/null
	RESULT="$?"
	echo $RESULT
	if [ $RESULT = 1 ]; then
		sketchybar --add item separator left
		sketchybar --set separator \
			label.drawing=on \
			label.color="$FOREGROUND" \
			label="|" \
			icon.drawing=off
	else
		sketchybar --clone "separator$1" separator
	fi
}

# CREATE BAR
sketchybar --bar height=45 \
	blur_radius=0 \
	position=bottom \
	sticky=off \
	padding_left=10 \
	corner_radius=0 \
	padding_right=10 \
	y_offset=0 \
	margin=0 \
	corner_radius=0 \
	color="$BACKGROUND"

# SET DEFAULTS
sketchybar --default updates=when_shown \
	drawing=on \
	icon.drawing=off \
	icon.font="$FONT:Regular:15.0" \
	icon.color="$FOREGROUND" \
	icon.padding_left=5 \
	icon.padding_right=5 \
	icon.background.height=28 \
	label.drawing=off \
	label.font="$FONT:Bold:15.0" \
	label.color="$FOREGROUND" \
	label.padding_left=5 \
	label.padding_right=5 \
	label.background.height=28 \
	background.drawing=off \
	background.corner_radius=5 \
	background.border_width=0 \
	background.padding_left=3 \
	background.padding_right=3 \
	popup.background.color="$BACKGROUND1"

# ADD ITEMS
# left
source "$ITEMS_DIR/imenu.sh"
separator 0
source "$ITEMS_DIR/ispace.sh"
separator 1
source "$ITEMS_DIR/iwindow.sh"

#center
source "$ITEMS_DIR/imode.sh"

# right
source "$ITEMS_DIR/iclock.sh"
source "$ITEMS_DIR/ivpn.sh"
source "$ITEMS_DIR/iwifi.sh"
source "$ITEMS_DIR/ibattery.sh"
source "$ITEMS_DIR/isound.sh"
source "$ITEMS_DIR/ialiases.sh"

sketchybar --update

echo "sketchybar configuration loaded.."
