---
- name: Init
  hosts: all
  become: false
  tags:
    - init
  tasks:
    - name: Brew Update
      when: (ansible_os_family == 'Darwin')
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      tags:
        - always
        - darwin

    - name: Dnf Update
      become: true
      when: (ansible_os_family == 'RedHat')
      ansible.builtin.dnf:
        autoremove: true
        update_cache: true
      tags:
        - always
        - fedora
        - linux

    - name: Dnf add distribution gpg
      become: true
      when: (ansible_os_family == 'RedHat')
      ansible.builtin.dnf:
        name: distribution-gpg-keys
        state: present
      tags:
        - essentials
        - fedora
        - linux

    - name: Enable the RPM Fusion repositories
      become: true
      when: ansible_distribution == 'Fedora'
      tags:
        - fedora
        - linux
      block:
        - name: Import a RPM Fusion free key
          ansible.builtin.rpm_key:
            state: present
            key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_version }}

        - name: Import a RPM Fusion nonfree key
          ansible.builtin.rpm_key:
            state: present
            key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_version }}

        - name: Enable repositories
          ansible.builtin.dnf:
            name:
              - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm"
              - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm"
            state: present

    - name: Apt Update
      become: true
      when: (ansible_os_family == 'Debian')
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        update_cache: true
      tags:
        - always
        - ubuntu
        - linux
