---
- name: Init
  hosts: all
  connection: local
  become: false
  tags:
    - init
    - work
  tasks:
    - name: Brew Update
      when: (ansible_os_family == 'Darwin')
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
      tags:
        - always

    - name: Dnf Update
      become: true
      when: (ansible_os_family == 'RedHat')
      tags:
        - always
      ansible.builtin.dnf:
        autoremove: true
        update_cache: true

    - name: Dnf dependencies
      become: true
      when: (ansible_os_family == 'RedHat')
      tags:
        - always
      ansible.builtin.dnf:
        name:
          - distribution-gpg-keys
          - python3-dnf
          - python3-libdnf5
        state: present

    - name: Apt Update
      become: true
      when: (ansible_os_family == 'Debian')
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        update_cache: true
      tags:
        - always
