---
- name: Init
  hosts: all
  become: false
  tasks:
    - name: Brew install
      ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      tags:
        - setup
      when: (ansible_os_family == 'Darwin')

    - name: Brew Update
      ansible.builtin.homebrew:
        update_homebrew: true
        upgrade_all: true
      tags:
        - init
        - always
      when: (ansible_os_family == 'Darwin')

    - name: dnf Update
      become: true
      ansible.builtin.dnf:
        autoremove: true
        update_cache: true
      tags:
        - always
      when: (ansible_os_family == 'RedHat')

    - name: dnf add distribution gpg
      become: true
      ansible.builtin.dnf:
         name: distribution-gpg-keys
         state: present
      tags:
        - essentials
      when: (ansible_os_family == 'RedHat')

    - name: Enable the RPM Fusion repositories
      become: true
      block:
        - name: Import a RPM Fusion free key
          ansible.builtin.rpm_key:
            state: present
            key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ansible_distribution_version}}

        - name: Import a RPM Fusion nonfree key
          ansible.builtin.rpm_key:
            state: present
            key: /usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ansible_distribution_version}}

        - name: enable repositories
          dnf:
            name:
              - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_version}}.noarch.rpm"
              - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_version}}.noarch.rpm"
            state: present
      when: ansible_distribution == 'Fedora'

    - name: Apt Update
      become: true
      apt:
        autoclean: true
        autoremove: true
        update_cache: true
      tags:
        - always
      when: (ansible_os_family == 'Debian')
