---
- name: Install Essentials
  hosts: all
  become: false
  tasks:
    - name: Set fact to become or not
      block:
        - name: Set become to true for linux
          ansible.builtin.set_fact:
            become_value: true
          when: ansible_system == "Linux"

        - name: Set become to false for darwin
          ansible.builtin.set_fact:
            become_value: false
          when: ansible_system == "Darwin"

    - name: Essential packages
      become: "{{ become_value }}"
      ansible.builtin.package:
        name:
          - zsh
          - git
          - vim
          - curl
          - wget
          - gcc
          - make
          - unzip
          - gnupg
          - ca-certificates
      tags: essentials

    - name: Common cli tools
      become: "{{ become_value }}"
      ansible.builtin.package:
        name:
          - jq
          - fzf
          - grc
          - htop
          - stow
          - ranger
          - ripgrep
          - neofetch
      tags: cli

    - name: Linux common cli tools
      become: true
      ansible.builtin.package:
        name:
          - g++
          - plocate
      tags: cli
      when: ansible_system == 'Linux'

    - name: Debian essentials
      become: true
      ansible.builtin.apt:
        name:
          - build-essential
          - software-properties-common
          - libreadline-dev
      tags: essentials
      when: ansible_os_family == 'Debian'

    - name: Redhat essentials
      become: true
      ansible.builtin.dnf:
        name:
          - kernel-devel
          - dnf-plugins-core
      tags: essentials
      when: ansible_os_family == 'RedHat'

    - name: Darwin essentials
      community.general.homebrew:
        name:
          - coreutils
      tags: essentials
      when: (ansible_os_family == 'Darwin')
