---
  # TODO: ubuntu cli
  # TODO: remove de from ubuntu
  # TODO: jdk only 21
  # TODO: ansible in base venv using pipx with latest python
  # TODO: pyenv python latest
  # TODO: node latest lts and electron node
  # TODO: go only when specified
  # TODO: rust only when specified
  # TODO: run-ansible script profiles work/local
  # TODO: tagging
- name: Install Essentials
  hosts: all
  connection: local
  become: false
  tags:
    - essentials
    - work
  tasks:
    - name: Set fact to become or not
      block:
        - name: Set become to true for linux
          when: ansible_system == "Linux"
          ansible.builtin.set_fact:
            become_value: true

        - name: Set become to false for darwin
          when: ansible_system == "Darwin"
          ansible.builtin.set_fact:
            become_value: false

    - name: Essential packages
      become: "{{ become_value }}"
      ansible.builtin.package:
        name:
          - zsh
          - git
          - curl
          - wget2
          - gcc
          - make
          - cmake
          - unzip
          - gnupg
          - ca-certificates

    - name: Common cli tools
      become: "{{ become_value }}"
      ansible.builtin.package:
        name:
          - jq
          - fzf
          - bat
          - grc
          - nnn
          - btop
          - p7zip
          - ripgrep

    - name: Build and Install Stow Latest
      tags:
        - stow
      block:
        - name: Download and Install stow if not latest
          block:
            - name: Validate stow is installed
              ansible.builtin.shell: |
                set -o pipefail
                /usr/local/bin/stow --version | grep "2.4.1" && touch /tmp/stow-version
              args:
                executable: /bin/bash
                creates: /tmp/stow-version
          rescue:
            - name: Download source code
              ansible.builtin.get_url:
                url: https://ftp.gnu.org/gnu/stow/stow-2.4.1.tar.gz
                dest: /tmp/stow.tar.gz
                timeout: 120
                mode: '0744'

            - name: Extract source code
              ansible.builtin.unarchive:
                src: /tmp/stow.tar.gz
                dest: /tmp/
                remote_src: true

            - name: Configure stow project
              become: true
              ansible.builtin.command:
                cmd: ./configure
                chdir: /tmp/stow-2.4.1
              register: configure_stow
              changed_when: configure_stow.rc != 0

            - name: Install stow
              become: true
              ansible.builtin.command:
                cmd: make install
                chdir: /tmp/stow-2.4.1
                creates: /usr/local/bin/stow

    - name: Linux common cli tools
      become: true
      when: ansible_system == 'Linux'
      ansible.builtin.package:
        name:
          - g++
          - plocate
          - fd-find

    - name: Debian essentials
      become: true
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        name:
          - vim-gtk3
          - build-essential
          - software-properties-common
          - libreadline-dev
          - libssl-dev
          - libbz2-dev
          - libffi-dev

    - name: Redhat essentials
      become: true
      when: ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        name:
          - vim-enhanced
          - kernel-devel
          - dnf-plugins-core

    - name: Darwin essentials
      when: (ansible_os_family == 'Darwin')
      community.general.homebrew:
        name:
          - fd
          - vim
          - coreutils

    - name: Clone dotfiles if not present # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/csd1100/dotfiles.git
        dest: ~/dotfiles
        clone: true
        update: false
        recursive: false
