---
- name: Install Essentials
  hosts: all
  become: false
  tasks:
    - name: essential packages
      become: true
      ansible.builtin.package:
        name:
          - zsh
          - git
          - vim
          - curl
          - wget
          - gcc
          - g++
          - make
          - unzip
          - gnupg
          - ca-certificates
        state: latest
      tags: essentials

    - name: common cli tools
      become: true
      ansible.builtin.package:
        name:
          - jq
          - fzf
          - grc
          - htop
          - stow
          - ranger
          - ripgrep
          - neofetch
        state: latest
      tags: cli

    - name: linux common cli tools
      become: true
      ansible.builtin.package:
        name:
          - plocate
        state: latest
      tags: cli
      when: ansible_system == 'Linux'

    - name: debian essentials
      become: true
      ansible.builtin.apt:
        name:
          - build-essential
          - software-properties-common
          - libreadline-dev
        state: latest
      tags: essentials
      when: (ansible_os_family == 'Debian')

    - name: redhat essentials
      become: true
      ansible.builtin.dnf:
        name:
          - kernel-devel
          - dnf-plugins-core
        state: latest
      tags: essentials
      when: (ansible_os_family == 'RedHat')

    - name: darwin essentials
      ansible.builtin.homebrew:
        name:
          - coreutils
        state: latest
      tags: essentials
      when: (ansible_os_family == 'Darwin')
