---
- name: Install Essentials
  hosts: localhost
  connection: local
  become: false
  tags:
    - essentials
  tasks:
    - name: Set fact to become or not
      block:
        - name: Set become to true for linux
          when: ansible_system == "Linux"
          ansible.builtin.set_fact:
            become_value: true
          tags:
            - linux

        - name: Set become to false for darwin
          when: ansible_system == "Darwin"
          ansible.builtin.set_fact:
            become_value: false
          tags:
            - darwin

    - name: Essential packages
      become: "{{ become_value }}"
      ansible.builtin.package:
        name:
          - zsh
          - git
          - curl
          - wget2
          - gcc
          - make
          - cmake
          - unzip
          - gnupg
          - ca-certificates
      tags:
        - darwin
        - linux

    - name: Common cli tools
      become: "{{ become_value }}"
      ansible.builtin.package:
        name:
          - jq
          - fzf
          - bat
          - grc
          - nnn
          - cmus
          - btop
          - unrar
          - ripgrep
          - neofetch
      tags:
        - cli
        - darwin
        - linux

    - name: Linux common cli tools
      become: true
      when: ansible_system == 'Linux'
      ansible.builtin.package:
        name:
          - g++
          - plocate
          - fd-find
      tags:
        - cli
        - linux

    - name: Debian essentials
      become: true
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        name:
          - vim-gtk3
          - build-essential
          - software-properties-common
          - libreadline-dev
      tags:
        - ubuntu
        - linux

    - name: Debian Install Stow Latest
      when: ansible_os_family == 'Debian'
      block:
        - name: Download source code
          ansible.builtin.get_url:
            url: https://ftp.gnu.org/gnu/stow/stow-latest.tar.gz
            dest: /tmp/stow.tar.gz

        - name: Extract source code
          ansible.builtin.unarchive:
            src: /tmp/stow.tar.gz
            dest: /tmp/stow
            remote_src: yes

        - name: Install stow
          become: true
          ansible.builtin.command:
            cmd: ./configure && make install
            chdir: /tmp/stow
            creates: /usr/bin/stow

    - name: Redhat essentials
      become: true
      when: ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        name:
          - stow
          - vim-X11
          - kernel-devel
          - dnf-plugins-core
      tags:
        - fedora
        - linux

    - name: Darwin essentials
      when: (ansible_os_family == 'Darwin')
      community.general.homebrew:
        name:
          - fd
          - vim
          - stow
          - coreutils
      tags:
        - cli
        - darwin
