---
- name: Install Desktop Environment
  tags:
    - de
  hosts: all
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Linux desktop environment
      tags:
        - linux
      block:
        - name: Xorg desktop environment (i3, polybar, rofi, picom)
          tags:
            - never
            - x11
          become: true
          when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
          ansible.builtin.package:
            name:
              - i3
              - feh
              - rofi
              - picom
              - scrot
              - xclip
              - polybar
              - xdotool
              - numlockx

        - name: Wayland desktop environment
          tags:
            - wayland
            - fedora
          block:
            - name: Wayland dependencies
              become: true
              tags:
                - ubuntu
              ansible.builtin.package:
                name:
                  - xev
                  - wev
                  - wofi
                  - wlr-randr
                  - xdg-utils
                  - pipewire
                  - wireplumber

            - name: Fedora hyprland setup
              when: ansible_distribution == "Fedora" and
                ansible_distribution_version == "39"
              block:
                - name: Create git-clones directory for building
                  ansible.builtin.file:
                    path: ~/work/git-clones/
                    state: directory
                    mode: '766'

                - name: Install hyprland packages fedora
                  become: true
                  ansible.builtin.dnf:
                    name:
                      - gdm
                      - swaylock
                      - kwallet
                      - polkit-kde
                      - pam-kwallet
                      - grim
                      - glibc
                      - libgcc
                      - wlroots
                      - hyprland
                      - file-devel
                      - gtk3-devel
                      - ninja-build
                      - glib2-devel
                      - glibc-devel
                      - pango-devel
                      - cairo-devel
                      - wlroots-devel
                      - qt5-qtwayland
                      - qt6-qtwayland
                      - wayland-devel
                      - libwebp-devel
                      - hyprland-devel
                      - libglvnd-devel
                      - gdk-pixbuf2-devel
                      - libglvnd-core-devel
                      - libjpeg-turbo-devel
                      - gtk-layer-shell-devel
                      - wayland-protocols-devel
                      - xdg-desktop-portal-hyprland

                - name: Install hyprlang
                  block:
                    - name: Clone hyprlang
                      ansible.builtin.git:
                        repo: https://github.com/hyprwm/hyprlang
                        dest: ~/work/git-clones/hyprlang
                        version: main

                    - name: Build hyprlang
                      args:
                        chdir: ~/work/git-clones/hyprlang
                        creates: ~/work/git-clones/hyprlang/build/libhyprlang.so.*
                      ansible.builtin.shell: |
                        cmake --no-warn-unused-cli -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -S . -B ./build
                        cmake --build ./build --config Release --target hyprlang -j`nproc 2>/dev/null || getconf NPROCESSORS_CONF`

                    - name: Install hyprlang
                      become: true
                      args:
                        chdir: "/home/{{ the_user }}/work/git-clones/hyprlang"
                        creates: /usr/lib64/libhyprlang.so
                      ansible.builtin.command:
                        cmake --install ./build

                - name: Check if hyprpaper is installed
                  ansible.builtin.stat:
                    path: ~/bin/hyprpaper
                  register: hyprpaper_stat

                - name: Install hyprpaper
                  when: not hyprpaper_stat.stat.exists
                  block:
                    - name: Clone hyprpaper
                      ansible.builtin.git:
                        repo: https://github.com/hyprwm/hyprpaper
                        dest: ~/work/git-clones/hyprpaper
                        version: main

                    - name: Build hyprpaper
                      community.general.make:
                        target: all
                        chdir: ~/work/git-clones/hyprpaper

                    - name: Copy hyprpaper to ~/bin
                      ansible.builtin.copy:
                        src: ~/work/git-clones/hyprpaper/build/hyprpaper
                        dest: ~/bin/hyprpaper
                        remote_src: true
                        mode: '544'

                - name: Check if Eww is installed
                  ansible.builtin.stat:
                    path: ~/bin/eww
                  register: eww_stat

                - name: Install Eww
                  when: not eww_stat.stat.exists
                  block:
                    - name: Clone Eww
                      ansible.builtin.git:
                        repo: https://github.com/elkowar/eww
                        dest: ~/work/git-clones/eww
                        version: master

                    - name: Build Eww
                      ansible.builtin.shell: |
                        cargo build --release --no-default-features --features=wayland
                      args:
                        chdir: ~/work/git-clones/eww
                        creates: ~/work/git-clones/eww/target/release/eww

                    - name: Copy Eww to ~/bin
                      ansible.builtin.copy:
                        src: ~/work/git-clones/eww/target/release/eww
                        dest: ~/bin/eww
                        remote_src: true
                        mode: '544'

            - name: Wayland clipboard
              tags:
                - ubuntu
              block:
                - name: Install wl-clipboard
                  become: true
                  ansible.builtin.package:
                    name:
                      - wl-clipboard

                - name: Install latest cliphist from github
                  block:
                    - name: Cliphist get latest release url from github
                      ansible.builtin.uri:
                        url: https://api.github.com/repos/sentriz/cliphist/releases/latest
                        return_content: true
                      register: cliphist_latest

                    - name: Store cliphist latest download url
                      ansible.builtin.set_fact:
                        cliphist_url: >
                          {{ cliphist_latest.json.assets | to_json | from_json |
                            community.general.json_query(browser_download_url_query) }}
                      vars:
                        browser_download_url_query: '[?browser_download_url.contains(@, `amd64`)] |
                            [0].browser_download_url'

                    - name: Copy cliphist to ~/bin
                      ansible.builtin.get_url:
                        url: "{{ cliphist_url }}"
                        dest: ~/bin/cliphist
                        mode: '544'

        - name: Common Linux desktop utilities
          become: true
          ansible.builtin.package:
            name:
              - dunst
              - playerctl
              - pavucontrol
          tags:
            - x11
            - wayland
            - ubuntu
            - fedora

    - name: Darwin desktop environment
      tags:
        - darwin
      environment:
        PATH: /usr/local/bin:/opt/homebrew/path:{{ ansible_env.PATH }}
      when: ansible_os_family == "Darwin"
      block:
        - name: Add sketchybar tap
          community.general.homebrew_tap:
            name:
              - FelixKratz/formulae

        - name: Install yabai, skhd, sketchybar
          community.general.homebrew:
            name:
              - koekeishiya/formulae/yabai
              - koekeishiya/formulae/skhd
              - sketchybar

        - name: Get yabai path
          ansible.builtin.command:
            which yabai
          register: yabai_path

        - name: Run visudo checksum to start yabai with script-additions
          ansible.builtin.command: /usr/local/bin/shasum -a 256 {{ yabai_path.stdout }}
          register: shasum_yabai

        - name: Create sudoers file
          become: true
          ansible.builtin.lineinfile:
            path: /private/etc/sudoers.d/yabai
            line: "{{ ansible_user_id }} ALL=(root) NOPASSWD: sha256:{{ shasum_yabai.stdout }} --load-sa"
            create: true
            mode: '440'
