---
- name: Install Desktop Environment
  tags:
    - de
  hosts: all
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
    - name: Linux desktop environment
      tags:
        - linux
        - fedora
        - ubuntu
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
      block:
        - name: Xorg desktop environment (i3, polybar, rofi, picom)
          tags:
            - never
            - x11
          become: true
          ansible.builtin.package:
            name:
              - i3
              - feh
              - xev
              - rofi
              - picom
              - scrot
              - xclip
              - polybar
              - xdotool
              - numlockx

        - name: Wayland desktop environment
          tags:
            - wayland
            - fedora
          block:
            - name: Wayland dependencies
              become: true
              tags:
                - ubuntu
              ansible.builtin.package:
                name:
                  - xev
                  - wev
                  - wofi
                  - wlr-randr
                  - xdg-utils
                  - waybar
                  - pipewire
                  - wireplumber

            - name: Fedora hyprland setup
              when: ansible_distribution == "Fedora" and
                ansible_distribution_version | int > 38
              tags:
                - fedora
              block:
                - name: Create git-clones directory for building
                  ansible.builtin.file:
                    path: ~/work/git-clones/
                    state: directory
                    mode: '766'

                - name: Add hyprland dnf copr
                  become: true
                  when: ansible_os_family == 'RedHat'
                  community.general.copr:
                    name: solopasha/hyprland

                - name: Install hyprland packages fedora
                  become: true
                  ansible.builtin.dnf:
                    name:
                      - hyprland-git
                      - hyprpaper
                      - hyprpicker
                      - hypridle
                      - hyprlock
                      - hyprland-git-devel
                      - eww-git
                      - gdm
                      - grim
                      - glibc
                      - libgcc
                      - wlroots
                      - kwallet
                      - pam-devel
                      - sdbus-cpp
                      - file-devel
                      - gtk3-devel
                      - polkit-kde
                      - pam-kwallet
                      - ninja-build
                      - glib2-devel
                      - glibc-devel
                      - pango-devel
                      - cairo-devel
                      - wlroots-devel
                      - qt5-qtwayland
                      - qt6-qtwayland
                      - wayland-devel
                      - libwebp-devel
                      - libglvnd-devel
                      - sdbus-cpp-devel
                      - gdk-pixbuf2-devel
                      - libglvnd-core-devel
                      - libjpeg-turbo-devel
                      - gtk-layer-shell-devel
                      - wayland-protocols-devel
                      - xdg-desktop-portal-hyprland

            - name: Wayland clipboard
              tags:
                - ubuntu
              block:
                - name: Install wl-clipboard
                  become: true
                  ansible.builtin.package:
                    name:
                      - wl-clipboard

                - name: Install latest cliphist from github
                  block:
                    - name: Cliphist get latest release url from github
                      ansible.builtin.uri:
                        url: https://api.github.com/repos/sentriz/cliphist/releases/latest
                        return_content: true
                      register: cliphist_latest

                    - name: Store cliphist latest download url
                      ansible.builtin.set_fact:
                        cliphist_url: >
                          {{ cliphist_latest.json.assets | to_json | from_json |
                            community.general.json_query(browser_download_url_query) }}
                      vars:
                        browser_download_url_query: '[?browser_download_url.contains(@, `amd64`)] |
                            [0].browser_download_url'

                    - name: Copy cliphist to ~/bin
                      ansible.builtin.get_url:
                        url: "{{ cliphist_url }}"
                        dest: ~/bin/cliphist
                        mode: '544'

        - name: Common Linux desktop utilities
          become: true
          ansible.builtin.package:
            name:
              - dunst
              - playerctl
              - pavucontrol
          tags:
            - x11
            - wayland
            - ubuntu
            - fedora

    - name: Darwin desktop environment
      tags:
        - darwin
      environment:
        PATH: /usr/local/bin:/opt/homebrew/path:{{ ansible_env.PATH }}
      when: ansible_os_family == "Darwin"
      block:
        - name: Add sketchybar, yabai taps
          community.general.homebrew_tap:
            name:
              - FelixKratz/formulae
              - koekeishiya/formulae

        - name: Install yabai, skhd, sketchybar
          community.general.homebrew:
            name:
              - yabai
              - skhd
              - sketchybar

        - name: Get yabai path
          ansible.builtin.command:
            which yabai
          register: yabai_path

        - name: Run visudo checksum to start yabai with script-additions
          ansible.builtin.command: /usr/bin/shasum -a 256 {{ yabai_path.stdout }}
          register: shasum_yabai

        - name: Create sudoers file
          become: true
          ansible.builtin.lineinfile:
            path: /private/etc/sudoers.d/yabai
            line: "{{ ansible_user_id }} ALL=(root) NOPASSWD: sha256:{{ shasum_yabai.stdout }} --load-sa"
            create: true
            mode: '440'
