---
- name: Install Desktop Environment
  hosts: all
  become: false
  tasks:
    - name: Linux desktop environment
      become: true
      ansible.builtin.package:
        name:
          - picom
          - i3
          - polybar
          - rofi
          - feh
          # - pulseaudio
          - pavucontrol
          - playerctl
      when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

    - name: Darwin desktop environment
      environment:
        PATH: /usr/local/bin:/opt/homebrew/path:{{ ansible_env.PATH }}
      when: ansible_os_family == "Darwin"
      block:
        - name: Add sketchybar tap
          community.general.homebrew_tap:
            name:
              - FelixKratz/formulae

        - name: Install yabai, skhd, sketchybar
          community.general.homebrew:
            name:
              - koekeishiya/formulae/yabai
              - koekeishiya/formulae/skhd
              - sketchybar

        - name: Get yabai path
          ansible.builtin.command:
            which yabai
          register: yabai_path

        - name: Test
          ansible.builtin.debug:
            msg: "{{ yabai_path }}"

        - name: Run visudo checksum to start yabai with script-additions
          ansible.builtin.command: /usr/local/bin/shasum -a 256 {{ yabai_path.stdout }}
          register: shasum_yabai

        - name: Create sudoers file
          become: true
          ansible.builtin.lineinfile:
            path: /private/etc/sudoers.d/yabai
            line: "{{ ansible_user_id }} ALL=(root) NOPASSWD: sha256:{{ shasum_yabai.stdout }} --load-sa"
            create: true
            mode: '440'
