#!/bin/bash
THEME=$(xrdb -get rofi.display.theme)
avail_outputs=($(xrandr | grep ' connected' | sed -En "s/ .*//p"))
if [[ ${#avail_outputs[@]} > 1 ]]; then
    avail_outputs+=("Main Only")
    avail_outputs+=("All")
    avail_outputs+=("Replicate")
fi
selected=$(( IFS=$'\n'; echo "${avail_outputs[*]}" ) | rofi -dmenu -p Outputs -theme $THEME)

case $selected in
    "All")
        xrandr --output ${avail_outputs[0]} --mode 1920x1080 
        for u in "${avail_outputs[@]}"
        do
            if [ "$u" != "${avail_outputs[0]}" ]; then
                xrandr --output $u --mode 1920x1080 --right-of ${avail_outputs[0]}
            fi
        done
    ;;
    "Replicate")
        xrandr --output ${avail_outputs[0]} --mode 1920x1080 
        for u in "${avail_outputs[@]}"
        do
            if [ "$u" != "${avail_outputs[0]}" ]; then
                xrandr --output $u --mode 1920x1080 --same-as ${avail_outputs[0]} 
            fi
        done
    ;;
    "Main Only")
        for u in "${avail_outputs[@]}"
        do
            if [ "$u" != "${avail_outputs[0]}" ]; then
                xrandr --output $u --off
            fi
        done
    ;;
    "")
        exit 99
    ;;
    *)
        xrandr --output $selected --mode 1920x1080 
        for u in "${avail_outputs[@]}"
        do
            if [ "$u" != "$selected" ]; then
                xrandr --output $u --off
            fi
        done
    ;;
esac
$(xrdb -get script.loc)/reloader