#!/bin/bash

THEME=$(xrdb -get rofi.power.theme)
OPTIONS="Lock
Logout
Power Off
Restart"
SELECTED=$(( IFS=$'\n'; echo "$OPTIONS" ) | rofi -dmenu -p "Power Menu" -theme $THEME)

case $SELECTED in
    "Lock")
        $(xrdb -get script.loc)/lock-screen
    ;;
    "Logout")
        i3-msg exit
    ;;
    "Restart")
        systemctl reboot
    ;;
    "Power Off")
        systemctl poweroff
    ;;
    *)
    ;;
esac