- name: Brew install
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  tags:
    - never
    - brew-init

- name: Brew Update
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true
  tags:
    - always

- name: git install (Brew)
  community.general.homebrew:
    name: git
  tags:
    - cli
    - essentials

- name: curl install (Brew)
  community.general.homebrew:
    name: curl
  tags:
    - cli
    - essentials

- name: wget install (Brew)
  community.general.homebrew:
    name: wget
  tags:
    - cli
    - essentials

- name: htop install (Brew)
  community.general.homebrew:
    name: htop
  tags:
    - cli
    - essentials

- name: GNU coreutils install (Brew)
  community.general.homebrew:
    name: coreutils
  tags:
    - cli
    - essentials

- name: zsh install (Brew)
  community.general.homebrew:
    name: zsh
  tags:
    - zsh
    - cli
    - essentials

- name: GNU stow install (Brew)
  community.general.homebrew:
    name: stow
  tags:
    - cli

- name: imagemagick install (Brew)
  community.general.homebrew:
    name: imagemagick
  tags:
    - gui
    - kitty

- name: ripgrep install (Brew)
  community.general.homebrew:
    name: ripgrep
  tags:
    - cli
    - nvim
    - essentials

- name: luarocks install (Brew)
  community.general.homebrew:
    name: luarocks
  tags:
    - cli
    - nvim

- name: nvim-nightly install (Brew)
  community.general.homebrew:
    name: nvim
    state: head
  tags:
    - cli
    - nvim
    - essentials

- name: neofetch install (Brew)
  community.general.homebrew:
    name: neofetch
  tags:
    - cli

- name: jq install (Brew)
  community.general.homebrew:
    name: jq
  tags:
    - cli
    - essentials

- name: yabai install (Brew)
  community.general.homebrew:
    name: yabai
  tags:
    - gui
    - de

- name: skhd install (Brew)
  community.general.homebrew:
    name: sketchybar
  tags:
    - gui
    - de

- name: sketchybar install (Brew)
  community.general.homebrew:
    name: sketchybar
  tags:
    - gui
    - de

- name: ranger install (Brew)
  community.general.homebrew:
    name: ranger
  tags:
    - cli

- name: kitty install (shell) (Darwin)
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    creates: /Applications/kitty.app
  tags:
    - gui
    - kitty

- name: Dotfiles Setup (Darwin)
  shell: cd ~/dotfiles && DOTFILES=~/dotfiles ./scripts/setup darwin
  tags:
  - dotfiles

- name: enable sketchybar service (Brew)
  shell: brew services start sketchybar
  tags:
    - gui
    - de

- name: enable skhd service (Brew)
  shell: brew services start skhd
  tags:
    - gui
    - de

- name: Create a fonts directory if it does not exist (Darwin)
  file:
    path: ~/Library/Fonts
    state: directory
    mode: '0755'
  tags: dotfiles

- name: Copy fonts (Darwin)
  copy:
    src: ~/dotfiles/fonts/
    dest: ~/Library/Fonts
  tags: dotfiles
