#!/usr/bin/env zsh
zstyle ':completion:*' use-cache yes
export ZSH="$HOME/.oh-my-zsh"

plugins=(
    git
    fzf
    npm
    dnf
    rust
    brew
    volta
    gradle
    grunt
    docker
    ubuntu
    kubectl
    zsh-completions
    zsh-autosuggestions
    zsh-syntax-highlighting
)


source "$HOME/env/env-vars"
source "$ZSH/oh-my-zsh.sh"
bindkey -v
source "$HOME/env/aliases"
source "$HOME/env/functions"
source "$HOME/env/misc"

eval "$(starship init zsh)"
