#!/usr/bin/env zsh
zstyle ':completion:*' use-cache yes
export ZSH="$HOME/.oh-my-zsh"

plugins=(
    git
    npm
    dnf
    rust
    brew
    volta
    grunt
    macos
    gradle
    docker
    ubuntu
    golang
    vi-mode
    fzf
    kubectl
    zsh-autosuggestions
    zsh-syntax-highlighting
)


# here sequence matters of env going first before oh-my-zsh
source "$HOME/env/env-vars"

source "$ZSH/oh-my-zsh.sh"

source "$HOME/env/misc"
source "$HOME/env/aliases"
source "$HOME/env/functions"

eval "$(starship init zsh)"
