- name: Debian-based Linux Setup
  include_tasks: linux/apt.yml
  when: ansible_os_family == "Debian"
  tags: always

- name: ArchLinux Setup
  include_tasks: linux/pacman.yml
  when: ansible_os_family == "ArchLinux"
  tags: always

- name: RadHat-based Linux Setup
  include_tasks: linux/dnf.yml
  when: ansible_os_family == "RedHat"
  tags: always

- name: kitty install (shell) (Linux)
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    creates: ~/.local/kitty.app/
  tags:
    - gui
    - kitty

- name: create kitty desktop file (Linux)
  shell: cd ~/dotfiles/kitty/.config/kitty && ./kitty-desktop
  tags:
    - kitty

- name: Dotfiles Linux Setup
  include_tasks: dotfiles.yml
  tags: always
