#!/usr/bin/env bash
THEME=$(xrdb -get rofi.audio.theme)

menu+=("Mute")
menu+=($(seq 0 10 100))
menu+=($(seq 125 25 250))

selected=$(( IFS=$'\n'; echo "${menu[*]}" ) | rofi -dmenu -p Level -theme $THEME)

case $selected in
    "Mute")
        pactl set-sink-mute @DEFAULT_SINK@ toggle 
    ;;
    *)
        if [ -z "$selected" ]
        then
            echo "EMPTY"
        else
             pactl set-sink-volume @DEFAULT_SINK@ "$selected"%
        fi
    ;;
esac