#!/usr/bin/env bash
THEME="~/.config/rofi/rofi.rasi"

menu=("Play/Pause")
menu+=("Next")
menu+=("Previous")
menu+=("Stop")

selected=$(( IFS=$'\n'; echo "${menu[*]}" ) | rofi -dmenu -p "$(playerctl metadata --format "{{ title }} - {{ artist }}")" -theme $THEME)

case $selected in
    "Play/Pause")
        playerctl play-pause
    ;;
    "Next")
        playerctl next
    ;;
    "Previous")
        playerctl previous
    ;;
    "Stop")
        playerctl stop
    ;;
    *)
    ;;
esac
