#!/usr/bin/env bash

THEME=$ROFI_THEME
OPTIONS="Lock
Logout
Power Off
Restart"
SELECTED=$(( IFS=$'\n'; echo "$OPTIONS" ) | rofi -dmenu -p "Power Menu" -theme $THEME)

case $SELECTED in
    "Lock")
        $ROFI_THEME
    ;;
    "Logout")
        i3-msg exit
    ;;
    "Restart")
        systemctl reboot
    ;;
    "Power Off")
        systemctl poweroff
    ;;
    *)
    ;;
esac
