#!/usr/bin/env bash
MODI=$1
THEME=$ROFI_THEME
case $MODI in
run)
    echo run
    rofi -rnow -run-command "zsh -i -c '{cmd}'" -show run -theme $THEME
    ;;
apps)
    rofi -show drun -theme $THEME
    ;;
windows)
    rofi -show window -theme $THEME
    ;;
*) ;;

esac
