#!/usr/bin/env bash
MODI=$1
THEME="~/.config/rofi/rofi.rasi"
case $MODI in
run)
    echo run
    rofi -rnow -run-command "zsh -i -c '{cmd}'" -show run -theme $THEME
    ;;
apps)
    rofi -show drun -theme $THEME
    ;;
windows)
    rofi -show window -theme $THEME
    ;;
ssh)
    rofi -show ssh -theme $THEME
    ;;
*) ;;

esac
