#!/usr/bin/env bash
set -e

Y='\033[1;33m'
NOCOLOR='\033[0m'

dots_to_cleanup=(
    "$HOME/env"
    "$HOME/bin/helpers"
    "$HOME/.grc"
    "$HOME/.zshrc"
    "$HOME/.p10k.zsh"
    "$HOME/.vimrc"
    "$HOME/.ideavimrc"
    "$HOME/.dircolors"
    "$HOME/.config/mpv"
    "$HOME/.config/kitty"
    "$HOME/.config/nvim"
    "$HOME/.config/neofetch"
    "$HOME/.config/hypr"
    "$HOME/.config/dunst"
    "$HOME/.config/eww"
    "$HOME/.config/rofi"
    "$HOME/.config/sketchybar"
    "$HOME/.config/skhd"
    "$HOME/.config/yabai"
    "$HOME/.config/Code"
    "$HOME/.config/VSCodium"
    "$HOME/Library/Application Support/Code"
    "$HOME/Library/Application Support/VSCodium"
)

ARG=$1

case "$ARG" in
    -n|--no|--dry-run)
        DRY_RUN="true"
        echo "Executing Dry Run..."
        ;;
    -h|--help)
        help=$(cat << 'EOF'
dots-cleanup [OPTIONS]

    -n | --no | --dry-run   - Do not cleanup symlinks just print what is going to be
                            cleaned up
    -h | --help             - Print help(this) message.

EOF
)
        echo "$help"
        exit 0
        ;;
    *)
        ;;
esac

cleanup() {
    local -n items_to_cleanup=$1
    for item in "${items_to_cleanup[@]}"; do
        if [ -e "$item" ]; then
            if [ -L "$item" ]; then
                echo -e "Cleaning up $item"
                if [ -z "$DRY_RUN" ];then
                    rm "$item"
                fi
            elif [ -d "$item" ]; then
                echo -e "${Y}${item} is a directory.${NOCOLOR}"
                links_to_cleanup=$(find "$item" -maxdepth 1 -type l)
                cleanup links_to_cleanup
            else
                echo -e "${Y}${item} is neither directory nor symlink.${NOCOLOR}"
            fi
        fi
    done
}

cleanup dots_to_cleanup
