#!/usr/bin/env bash
set -e

if [ -z "$1" ]; then
	echo "Usage: run-ansible <user> [ansible-playbook args]" >&2
	exit 1
fi

pushd "$HOME/dotfiles/" || exit
./scripts/helpers/ansible-setup
ansible-playbook -i ./ansible/inventory.yml -u "$1" ./ansible/playbooks/main.yaml -kK "${@:2}"
popd || exit
