#!/bin/bash
SERVICE=$1

if pgrep -x "$SERVICE" >/dev/null
then
    echo "$SERVICE is running"
else
    echo "$SERVICE stopped"
    echo "starting $SERVICE"
    case $SERVICE in 
        nautilus)
            nautilus
        ;;
        *)
           $(cat /usr/share/applications/*"$SERVICE"* | grep -m 1 -E '^Exec=' | sed 's/^.*=//')
        ;;
    esac
fi