#!/usr/bin/env bash
set -e

ARG=$1

touch /tmp/dotfiles-setup

case "$ARG" in
darwin)
	declare -a config=("skhd" "yabai" "sketchybar")
	;;
linux)
	declare -a config=("i3" "polybar" "rofi" "i3status" "systemd")
	;;
common)
	declare -a config=("bin" "env" "kitty" "neofetch" "nvim" "tmux" "vim" "dircolors" "grc")
	;;
--single)
	config=("$2")
	;;
*)
	echo "Invalid argument; expected arguments: darwin/linux/common"
	exit 1
	;;
esac

pushd "$DOTFILES" >/dev/null

for util in "${config[@]}"; do
	./scripts/stower "$util"
done

if [ $ARG = "--single" ]; then
    echo "$2 setup" >>/tmp/dotfiles-setup
else
    echo "$ARG setup" >>/tmp/dotfiles-setup
fi

popd
