#!/usr/bin/env bash

windows () {
    hyprctl activewindow -j | jq -Mc "{
                                        id: .pid,
                                        initClass: .initialClass | ascii_downcase | sub(\" \";\"\";\"g\"),
                                        class: .class|ascii_downcase|sub(\" \";\"\";\"g\"),
                                        title: .title
                                    }"
}

windows
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	windows
done
