#!/usr/bin/env bash

spaces() {
    current=$(hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id')
    hyprctl workspaces -j | jq -Mc "map(select(.id != $current)) | map({key: .id, value: .windows}) | sort_by(.key|tonumber)"
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
