#!/usr/bin/env bash

windows() {
	WORKSPACE=$(hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id')
	hyprctl clients -j | jq --argjson wspace "$WORKSPACE" \
		--slurpfile icons ~/dotfiles/fonts/icon_map.json \
		-Mc 'map(select(.workspace.id == $wspace) |
            {
                id: .pid,
                initClass: .initialClass,
                class: .class,
                title: .title,
                icon: $icons.[0][.class]
            }
        )'
}

windows
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	windows
done
